name: Deploy-DB-Scripts

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest   # Windows runner for SQL Server tools

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SQL Server tools
        run: |
          choco install sqlcmd -y

      - name: Run SQL scripts on remote database
        shell: powershell
        run: |
          Get-ChildItem -Path "scripts\*.sql" | ForEach-Object {
            Write-Host "Running script $($_.Name)..."
            sqlcmd -S $env:DB_SERVER -U $env:DB_USER -P $env:DB_PASS -d $env:DB_NAME -i $_.FullName -b -o "logs_$($_.BaseName).txt"
          }
